version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    restart: unless-stopped
    ports:
      - '8085:8080'
    volumes:
     - img_decode:/app/img-decode
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_TIMEZONE: ${TIMEZONE}
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url" : "r2dbc:postgresql://$DB_HOST:$DB_PORT/$DB_DATABASE",
	"spring.r2dbc.username" : "${DB_USERNAME}",
	"spring.r2dbc.password" : "${DB_PASSWORD}",
	"minio.bucket" : "$MINIO_BUCKET",
	"minio.url" : "http://$MINIO_HOST:9000/",
	"minio.username" : "$MINIO_USERNAME",
	"minio.password" : "$MINIO_PASSWORD",
        "yandex.map.apikey" : "$YA_APIKEY",
	"spring.security.oauth2.client.registration.yandex.client-id" : "$YA_ID",
	"spring.security.oauth2.client.registration.yandex.client-secret" : "$YA_SECRET",
	"spring.security.oauth2.client.registration.yandex.redirect-uri" : "http://$APP_DOMAIN:8080/login/oauth2/code/{registrationId}",
        "spring.mail.host" : "$MAIL_SERVER",
        "spring.mail.username" : "$MAIL_USERNAME",
        "spring.mail.password" : "$MAIL_PASSWORD"
      }'


networks:
  default:
    name: ${DEPLOY_NETWORK_NAME}
    external: true
