version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    restart: unless-stopped
    ports:
      - '8085:8080'
    volumes:
     - img_decode:/src/main/resources/static/img
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_TIMEZONE: ${TIMEZONE}
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url" : "r2dbc:postgresql://$DB_HOST:$DB_PORT/$DB_DATABASE",
	"spring.r2dbc.username" : "${DB_USERNAME}",
	"spring.r2dbc.password" : "${DB_PASSWORD}",
	"spring.sql.init.mode" : "always",
	"minio.bucket" : "$MINIO_BUCKET",
	"minio.url" : "http://domensport-minio-1:9000",
	"minio.username" : "$MINIO_USERNAME",
	"minio.password" : "$MINIO_PASSWORD",
        "yandex.map.api" : "$YA_APIKEY",
	"spring.security.oauth2.client.registration.yandex.client-id" : "$YA_ID",
	"spring.security.oauth2.client.registration.yandex.client-secret" : "$YA_SECRET",
	"spring.security.oauth2.client.registration.yandex.redirect-uri" : "http://$APP_DOMAIN:8080/login/oauth2/code/{registrationId}",
	"spring.security.oauth2.client.registration.yandex.authorization-grant-type" : "authorization_code",
	"spring.security.oauth2.client.provider.yandex.authorization-uri" : "https://oauth.yandex.com/authorize",
	"spring.security.oauth2.client.provider.yandex.token-uri" : "https://oauth.yandex.com/token",
	"spring.security.oauth2.client.provider.yandex.user-info-uri" : "https://login.yandex.ru/info",
	"spring.security.oauth2.client.provider.yandex.user-name-attribute" : "id",
        "spring.mail.host" : "$MAIL_SERVER",
        "spring.mail.port" : "465",
        "spring.mail.username" : "$MAIL_USERNAME",
        "spring.mail.password" : "$MAIL_PASSWORD",
        "spring.mail.protocol" : "smtps",
        "spring.mail.properties.mail.smtp.auth" : "true",
        "spring.mail.properties.mail.smtp.socketFactory.port" : "465",
        "spring.mail.properties.mail.smtp.socketFactory.class" : "javax.net.ssl.SSLSocketFactory",
        "spring.mail.properties.mail.smtp.socketFactory.fallback" : "false"
      }'


networks:
  default:
    name: ${DEPLOY_NETWORK_NAME}
    external: true
