
services:
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data

  postgres:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
#      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ru-RU
#      LANG: ru_RU.UTF-8
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ../backup:/backup
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
networks:
  default:
    name: ${DEPLOY_NETWORK_NAME}
    external: true

volumes:
  postgres_data:
  minio_data:
  img_decode:
