create table if not exists ekp(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    num int,
    title text,
    beginning date,
    ending date,
    access text,
    category text,
    location text,
    ekp text,
    s float,
    d float
);

create table if not exists app_user(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username text,
    password text,
    firstname text,
    lastname text,
    email text,
    birthday date,
    placed_at date,
    avatar_id text
);